
export default {
    products:[
        {
            _id:"101",
            name:"Slim-Shirt",
            image:"/image/slim_shirt.jpg",
            price:10,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            countInStack:0
        },
        {
            _id:"102",
            name:"Fit-Shirt",
            image:"/image/slim_shirt.jpg",
            price:12,
            brand:"Nike",
            rating:4.6,
            numReviews:12,
            countInStack:9
        },
        {
            _id:"103",
            name:"Good-Shirt",
            image:"/image/slim_shirt.jpg",
            price:15,
            brand:"Mike",
            rating:4.0,
            numReviews:12,
            countInStack:1200
        },
        {
            _id:"104",
            name:"Slim-Shirt",
            image:"/image/slim_shirt.jpg",
            price:10,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            countInStack:500
        },
        {
            _id:"105",
            name:"nice-Shirt",
            image:"/image/slim_shirt.jpg",
            price:10,
            brand:"Nike",
            rating:4.5,
            numReviews:10,
            countInStack:5550
        },
    ]
}